import 'package:spry/config.dart';
import 'package:spry/openapi.dart';

void main() {
  defineSpryConfig(
    host: '127.0.0.1',
    port: 4010,
    target: BuildTarget.vm,
    openapi: OpenAPIConfig(
      document: OpenAPIDocumentConfig(
        info: OpenAPIInfo(
          title: 'Spry OpenAPI Example',
          version: '1.0.0',
          description: 'Example API document generated by Spry.',
        ),
        components: OpenAPIComponents(
          schemas: {
            'User': OpenAPISchema.object({
              'id': OpenAPISchema.ref('#/components/schemas/UserId'),
              'name': OpenAPISchema.string(),
            }),
          },
        ),
      ),
      output: OpenAPIOutput.route('openapi.json'),
    ),
  );
}
