name: spry
description: A starting point for Dart libraries or applications.
version: 4.0.0-dev.0

environment:
  sdk: ^3.4.3

dependencies:
  routingkit: ^1.1.0
  web_socket: ^0.1.5

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
