name: spry
description: Spry is a lightweight, composable Dart web framework designed to work collaboratively with various runtime platforms.
version: 4.1.0
homepage: https://spry.fun
repository: https://github.com/medz/spry

environment:
  sdk: ^3.4.3

dependencies:
  routingkit: ^1.1.0
  web: ^0.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
