name: spry
description: Spry is an HTTP middleware framework for Dart to make web applications and APIs server more enjoyable to write.
version: 1.0.0
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry

environment:
  sdk: ">=2.18.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
dependencies:
  meta: ^1.9.0
