name: spry
description: Spry is an HTTP middleware framework for Dart to make web applications and APIs server more enjoyable to write.
version: 3.3.1
homepage: https://spry.fun
repository: https://github.com/medz/spry

environment:
  sdk: ^3.2.0

dependencies:
  logging: ^1.2.0
  path: ^1.9.0
  routingkit: ^0.2.0
  webfetch: ^0.0.16

dev_dependencies:
  lints: ^4.0.0
  test: ^1.23.1
