name: spry
description: Spry is an HTTP middleware framework for Dart to make web applications and APIs server more enjoyable to write.
version: 2.0.1
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  meta: ^1.9.0
  mime: ^1.0.4

dev_dependencies:
  http: ^0.13.5
  lints: ^2.0.0
  test: ^1.23.1
