name: spry
description: Spry is a lightweight, composable Dart web framework designed to work collaboratively with various runtime platforms.
version: 4.0.0-dev.1
homepage: https://spry.fub
repository: https://github.com/medz/spry

environment:
  sdk: ^3.4.3

dependencies:
  routingkit: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
