name: spry_session
description: Spry extension for session management.
version: 1.1.0
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry_session

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  spry: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
