name: spry_multer
description: Spry multer is a Spry framework middleware & extension for handling multipart/form-data, which is primarily used for uploading files.
version: 1.1.0
homepage: https://spry.fun
repository: https://github.com/odroe/spry/tree/main/packages/spry_multer

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  mime: ^1.0.4
  spry: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
