name: spry_cookie
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

dependencies:
  http_parser: ^4.1.0
  spry:
    path: ../spry

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
