name: spry_cookie
description: Cookies Support for Spry.
version: 0.0.1
homepage: https://spry.fun/cookies
repository: https://github.com/medz/spry

environment:
  sdk: ^3.4.3

dependencies:
  crypto: ^3.0.3
  http_parser: ^4.1.0
  spry: ^4.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
