import 'dart:convert';

import 'package:path/path.dart' as p;
import 'package:ht/ht.dart' show HttpMethod;

import '../../config.dart';

import 'config.dart';
import 'generated_file.dart';
import 'route_tree.dart';
import 'target_spec.dart';

/// Generates framework entry files from a scanned route tree.
Future<List<GeneratedFile>> generate(RouteTree tree, BuildConfig config) async {
  final outputDir = p.join(config.rootDir, config.outputDir);
  // Generated Dart source files live in a dedicated src/ subdirectory so that
  // compiled output (JS, native binaries) can sit alongside them in separate
  // per-target subdirectories without mixing concerns.
  final genDir = p.join(outputDir, 'src');
  final sourceFiles = <String>{
    for (final entry in tree.routes) entry.filePath,
    for (final entry in tree.globalMiddleware) entry.filePath,
    for (final entry in tree.scopedMiddleware) entry.filePath,
    for (final entry in tree.scopedErrors) entry.filePath,
    if (tree.fallback case final fallback?) fallback.filePath,
    if (tree.hooks case final hooks?) hooks.filePath,
  }.toList()..sort();

  final aliases = <String, String>{};
  final imports = <String>[];
  for (var i = 0; i < sourceFiles.length; i++) {
    final filePath = sourceFiles[i];
    final relative = p.relative(filePath, from: genDir).replaceAll('\\', '/');
    final alias = '\$i$i';
    aliases[filePath] = alias;
    imports.add("import '$relative' as $alias;");
  }

  final routeGroups = <String, List<RouteEntry>>{};
  for (final route in tree.routes) {
    routeGroups.putIfAbsent(route.path, () => <RouteEntry>[]).add(route);
  }

  final app = StringBuffer()
    ..writeln("// Generated by spry - do not edit.")
    ..writeln(
      "import 'package:spry/spry.dart' show Spry, ErrorRoute, MiddlewareRoute;",
    );

  final usesHttpMethod =
      routeGroups.values.any(
        (entries) => entries.any((it) => it.method != null),
      ) ||
      tree.globalMiddleware.any((it) => it.method != null) ||
      tree.scopedMiddleware.any((it) => it.method != null) ||
      tree.scopedErrors.any((it) => it.method != null);
  if (usesHttpMethod) {
    app.writeln("import 'package:spry/spry.dart' show HttpMethod;");
  }

  for (final line in imports) {
    app.writeln(line);
  }

  app
    ..writeln()
    ..writeln('final app = Spry(')
    ..writeln('  routes: {');

  final sortedPaths = routeGroups.keys.toList()..sort();
  for (final path in sortedPaths) {
    final entries = routeGroups[path]!..sort(_compareRouteEntries);
    app.writeln("    '${_escape(path)}': {");
    for (final entry in entries) {
      final key = entry.method == null ? 'null' : _methodLiteral(entry.method!);
      final alias = aliases[entry.filePath]!;
      app.writeln('      $key: ${_handlerLiteral(alias)},');
    }
    app.writeln('    },');
  }

  app
    ..writeln('  },')
    ..writeln('  middleware: [');

  for (final entry in [...tree.globalMiddleware, ...tree.scopedMiddleware]) {
    final alias = aliases[entry.filePath]!;
    final methodPart = entry.method == null
        ? ''
        : ', method: ${_methodLiteral(entry.method!)}';
    app.writeln(
      "    MiddlewareRoute(path: '${_escape(entry.path)}'$methodPart, handler: $alias.middleware),",
    );
  }

  app
    ..writeln('  ],')
    ..writeln('  errors: [');

  for (final entry in tree.scopedErrors) {
    final alias = aliases[entry.filePath]!;
    final methodPart = entry.method == null
        ? ''
        : ', method: ${_methodLiteral(entry.method!)}';
    app.writeln(
      "    ErrorRoute(path: '${_escape(entry.path)}'$methodPart, handler: $alias.onError),",
    );
  }

  app.writeln('  ],');

  if (tree.fallback case final fallback?) {
    final alias = aliases[fallback.filePath]!;
    app
      ..writeln('  fallback: {')
      ..writeln('    null: ${_handlerLiteral(alias)},')
      ..writeln('  },');
  }

  if (config.target != BuildTarget.cloudflare) {
    app.writeln("  publicDir: '${_escape(config.publicDir)}',");
  }

  app.writeln(');');

  final hooksBuffer = StringBuffer()
    ..writeln("// Generated by spry - do not edit.");
  if (tree.hooks case final hooks?) {
    hooksBuffer
      ..writeln(
        "import '${_relativeImport(hooks.filePath, from: genDir)}' as \$source;",
      )
      ..writeln()
      ..writeln(
        hooks.hasOnStart
            ? 'final onStart = \$source.onStart;'
            : 'final onStart = null;',
      )
      ..writeln(
        hooks.hasOnStop
            ? 'final onStop = \$source.onStop;'
            : 'final onStop = null;',
      )
      ..writeln(
        hooks.hasOnError
            ? 'final onError = \$source.onError;'
            : 'final onError = null;',
      );
  } else {
    hooksBuffer
      ..writeln()
      ..writeln('final onStart = null;')
      ..writeln('final onStop = null;')
      ..writeln('final onError = null;');
  }
  final spec = buildTargetSpec(config);
  final main = _generateMain(spec);
  final files = <GeneratedFile>[
    GeneratedFile(path: 'src/app.dart', content: app.toString()),
    GeneratedFile(path: 'src/hooks.dart', content: hooksBuffer.toString()),
    GeneratedFile(path: 'src/main.dart', content: main),
  ];
  final openApiFile = _generateOpenApiDocument(tree, config);
  if (openApiFile != null) {
    files.add(openApiFile);
  }
  files.addAll(spec.extraFiles);
  return files;
}

int _compareRouteEntries(RouteEntry a, RouteEntry b) {
  if (a.method == null && b.method != null) {
    return -1;
  }
  if (a.method != null && b.method == null) {
    return 1;
  }
  return (a.method?.value ?? '').compareTo(b.method?.value ?? '');
}

String _handlerLiteral(String alias) => '$alias.handler';

String _escape(String value) =>
    value.replaceAll(r'$', r'\$').replaceAll("'", r"\'");

String _methodLiteral(HttpMethod method) => 'HttpMethod.${method.name}';

String _relativeImport(String filePath, {required String from}) {
  return p.relative(filePath, from: from).replaceAll('\\', '/');
}

GeneratedFile? _generateOpenApiDocument(RouteTree tree, BuildConfig config) {
  final openapiConfig = config.openapi;
  if (openapiConfig == null) {
    return null;
  }

  final paths = <String, Map<String, dynamic>>{};
  final liftedComponents = <Map<String, dynamic>>[];
  final routeGroups = <String, List<RouteEntry>>{};
  for (final route in tree.routes) {
    if (route.openapi == null) {
      continue;
    }
    routeGroups.putIfAbsent(route.path, () => <RouteEntry>[]).add(route);
  }

  for (final entry in routeGroups.entries) {
    final path = _toOpenApiPath(entry.key);
    final operations = <String, dynamic>{};
    Map<String, dynamic>? anyMethodOperation;
    final explicitOperations = <HttpMethod, Map<String, dynamic>>{};

    for (final route in entry.value) {
      final extracted = _extractGlobalComponents(route.openapi!);
      if (extracted.globalComponents != null) {
        liftedComponents.add(extracted.globalComponents!);
      }
      if (route.method == null) {
        anyMethodOperation = extracted.operation;
      } else {
        explicitOperations[route.method!] = extracted.operation;
      }
    }

    if (anyMethodOperation case final operation?) {
      for (final method in _openApiExpandedMethods) {
        operations[method] = _cloneJsonObject(operation);
      }
    }

    for (final explicit in explicitOperations.entries) {
      operations[explicit.key.name] = _cloneJsonObject(explicit.value);
    }

    if (operations.isNotEmpty) {
      paths[path] = operations;
    }
  }

  final document = _cloneJsonObject(_jsonObject(openapiConfig.document))
    ..['openapi'] = '3.1.0';
  final mergedComponents = _mergeDocumentComponents(
    switch (document['components']) {
      final Map components => Map<String, dynamic>.from(components),
      null => <String, dynamic>{},
      _ => throw StateError(
        'OpenAPI document components must be a JSON object.',
      ),
    },
    liftedComponents,
    openapiConfig.componentsMergeStrategy,
  );
  if (mergedComponents.isNotEmpty) {
    document['components'] = mergedComponents;
  } else {
    document.remove('components');
  }
  document['paths'] = paths;

  return switch (openapiConfig.output.type) {
    'route' => GeneratedFile(
      path: p.join(config.publicDir, openapiConfig.output.path),
      content: const JsonEncoder.withIndent('  ').convert(document),
      rootRelative: true,
    ),
    'local' => GeneratedFile(
      path: openapiConfig.output.path,
      content: const JsonEncoder.withIndent('  ').convert(document),
      rootRelative: true,
    ),
    _ => throw StateError(
      'Unsupported OpenAPI output type: ${openapiConfig.output.type}',
    ),
  };
}

const _openApiExpandedMethods = <String>[
  'get',
  'post',
  'put',
  'patch',
  'delete',
  'options',
];

const _globalComponentsKey = 'x-spry-openapi-global-components';

String _toOpenApiPath(String path) {
  return path
      .replaceAllMapped(
        RegExp(r'\*\*:([A-Za-z_][A-Za-z0-9_]*)'),
        (match) => '{${match[1]}}',
      )
      .replaceAllMapped(
        RegExp(r':([A-Za-z_][A-Za-z0-9_]*)(?:\([^)]*\))?[\?\+\*]?'),
        (match) => '{${match[1]}}',
      );
}

Map<String, dynamic> _jsonObject(dynamic value) {
  final encoded = jsonEncode(value);
  final decoded = jsonDecode(encoded);
  if (decoded is Map<String, dynamic>) {
    return decoded;
  }
  throw StateError('Expected a JSON object.');
}

Map<String, dynamic> _cloneJsonObject(Map<String, dynamic> value) =>
    Map<String, dynamic>.from(value);

Map<String, dynamic> _mergeDocumentComponents(
  Map<String, dynamic> base,
  List<Map<String, dynamic>> lifted,
  OpenAPIComponentsMergeStrategy strategy,
) {
  final result = _deepCloneJsonValue(base) as Map<String, dynamic>;
  for (final components in lifted) {
    for (final categoryEntry in components.entries) {
      final category = categoryEntry.key;
      final incomingBucket = categoryEntry.value;
      if (incomingBucket is! Map) {
        throw StateError(
          'OpenAPI components bucket `$category` must be a JSON object.',
        );
      }

      final existingBucket = result.putIfAbsent(
        category,
        () => <String, dynamic>{},
      );
      if (existingBucket is! Map) {
        throw StateError(
          'OpenAPI components bucket `$category` must be a JSON object.',
        );
      }

      final existingTyped = Map<String, dynamic>.from(existingBucket);
      result[category] = existingTyped;

      for (final componentEntry in incomingBucket.entries) {
        final name = '${componentEntry.key}';
        final incomingValue = _deepCloneJsonValue(componentEntry.value);
        if (!existingTyped.containsKey(name)) {
          existingTyped[name] = incomingValue;
          continue;
        }

        final currentValue = existingTyped[name];
        if (_jsonDeepEquals(currentValue, incomingValue)) {
          continue;
        }

        if (strategy == OpenAPIComponentsMergeStrategy.deepMerge) {
          existingTyped[name] = _deepMergeJsonValues(
            currentValue,
            incomingValue,
            context: 'components.$category.$name',
          );
          continue;
        }

        throw StateError('Conflicting OpenAPI component `$category.$name`.');
      }
    }
  }
  return result;
}

({Map<String, dynamic> operation, Map<String, dynamic>? globalComponents})
_extractGlobalComponents(Map<String, dynamic> operation) {
  final cloned = _cloneJsonObject(operation);
  final lifted = cloned.remove(_globalComponentsKey);
  if (lifted == null) {
    return (operation: cloned, globalComponents: null);
  }
  if (lifted is! Map) {
    throw StateError('`$_globalComponentsKey` must be a JSON object.');
  }
  return (
    operation: cloned,
    globalComponents: Map<String, dynamic>.from(lifted),
  );
}

Object? _deepMergeJsonValues(
  Object? current,
  Object? incoming, {
  required String context,
}) {
  if (current is Map && incoming is Map) {
    final result = Map<String, dynamic>.from(current);
    for (final entry in incoming.entries) {
      final key = '${entry.key}';
      if (!result.containsKey(key)) {
        result[key] = _deepCloneJsonValue(entry.value);
        continue;
      }
      result[key] = _deepMergeJsonValues(
        result[key],
        entry.value,
        context: '$context.$key',
      );
    }
    return result;
  }

  if (_jsonDeepEquals(current, incoming)) {
    return _deepCloneJsonValue(current);
  }

  throw StateError(
    'Conflicting OpenAPI component value at `$context` during deep merge.',
  );
}

Object? _deepCloneJsonValue(Object? value) {
  if (value is Map) {
    return {
      for (final entry in value.entries)
        '${entry.key}': _deepCloneJsonValue(entry.value),
    };
  }
  if (value is List) {
    return [for (final item in value) _deepCloneJsonValue(item)];
  }
  return value;
}

bool _jsonDeepEquals(Object? a, Object? b) {
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final entry in a.entries) {
      if (!b.containsKey(entry.key)) {
        return false;
      }
      if (!_jsonDeepEquals(entry.value, b[entry.key])) {
        return false;
      }
    }
    return true;
  }
  if (a is List && b is List) {
    if (a.length != b.length) {
      return false;
    }
    for (var i = 0; i < a.length; i++) {
      if (!_jsonDeepEquals(a[i], b[i])) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

String _generateMain(TargetSpec spec) {
  final buffer = StringBuffer()
    ..writeln("// Generated by spry - do not edit.")
    ..writeln("import 'package:spry/osrv.dart';")
    ..writeln(spec.runtimeImport);
  buffer
    ..writeln("import 'hooks.dart' as \$hooks;")
    ..writeln("import 'app.dart';")
    ..writeln()
    ..write(spec.mainBody);
  return buffer.toString();
}
