import 'package:path/path.dart' as p;
import 'package:ht/ht.dart' show HttpMethod;

import '../../config.dart';

import 'config.dart';
import 'route_tree.dart';

final class GeneratedFile {
  const GeneratedFile({required this.path, required this.content});

  final String path;
  final String content;
}

Future<List<GeneratedFile>> generate(RouteTree tree, BuildConfig config) async {
  final outputDir = p.join(config.rootDir, config.outputDir);
  final sourceFiles = <String>{
    for (final entry in tree.routes) entry.filePath,
    for (final entry in tree.globalMiddleware) entry.filePath,
    for (final entry in tree.scopedMiddleware) entry.filePath,
    for (final entry in tree.scopedErrors) entry.filePath,
    if (tree.fallback case final fallback?) fallback.filePath,
    if (tree.hooks case final hooks?) hooks.filePath,
  }.toList()..sort();

  final aliases = <String, String>{};
  final imports = <String>[];
  for (var i = 0; i < sourceFiles.length; i++) {
    final filePath = sourceFiles[i];
    final relative = p
        .relative(filePath, from: outputDir)
        .replaceAll('\\', '/');
    final alias = '\$i$i';
    aliases[filePath] = alias;
    imports.add("import '$relative' as $alias;");
  }

  final routeGroups = <String, List<RouteEntry>>{};
  for (final route in tree.routes) {
    routeGroups.putIfAbsent(route.path, () => <RouteEntry>[]).add(route);
  }

  final app = StringBuffer()
    ..writeln("// Generated by spry - do not edit.")
    ..writeln("import 'package:spry/src/app.dart';")
    ..writeln("import 'package:spry/src/error_route.dart';")
    ..writeln("import 'package:spry/src/middleware.dart';");

  final usesHttpMethod =
      routeGroups.values.any(
        (entries) => entries.any((it) => it.method != null),
      ) ||
      tree.globalMiddleware.any((it) => it.method != null) ||
      tree.scopedMiddleware.any((it) => it.method != null) ||
      tree.scopedErrors.any((it) => it.method != null);
  if (usesHttpMethod) {
    app.writeln("import 'package:ht/ht.dart' show HttpMethod;");
  }

  for (final line in imports) {
    app.writeln(line);
  }

  app
    ..writeln()
    ..writeln('final app = Spry(')
    ..writeln('  routes: {');

  final sortedPaths = routeGroups.keys.toList()..sort();
  for (final path in sortedPaths) {
    final entries = routeGroups[path]!..sort(_compareRouteEntries);
    app.writeln("    '${_escape(path)}': {");
    for (final entry in entries) {
      final key = entry.method == null ? 'null' : _methodLiteral(entry.method!);
      final alias = aliases[entry.filePath]!;
      app.writeln('      $key: $alias.handler,');
    }
    app.writeln('    },');
  }

  app
    ..writeln('  },')
    ..writeln('  middleware: [');

  for (final entry in [...tree.globalMiddleware, ...tree.scopedMiddleware]) {
    final alias = aliases[entry.filePath]!;
    final methodPart = entry.method == null
        ? ''
        : ', method: ${_methodLiteral(entry.method!)}';
    app.writeln(
      "    MiddlewareRoute(path: '${_escape(entry.path)}'$methodPart, handler: $alias.middleware),",
    );
  }

  app
    ..writeln('  ],')
    ..writeln('  errors: [');

  for (final entry in tree.scopedErrors) {
    final alias = aliases[entry.filePath]!;
    final methodPart = entry.method == null
        ? ''
        : ', method: ${_methodLiteral(entry.method!)}';
    app.writeln(
      "    ErrorRoute(path: '${_escape(entry.path)}'$methodPart, handler: $alias.onError),",
    );
  }

  app.writeln('  ],');

  if (tree.fallback case final fallback?) {
    final alias = aliases[fallback.filePath]!;
    app
      ..writeln('  fallback: {')
      ..writeln('    null: $alias.handler,')
      ..writeln('  },');
  }

  app.writeln(');');

  final hooksBuffer = StringBuffer()
    ..writeln("// Generated by spry - do not edit.");
  if (tree.hooks case final hooks?) {
    hooksBuffer
      ..writeln(
        "import '${_relativeImport(hooks.filePath, from: outputDir)}' as \$source;",
      )
      ..writeln()
      ..writeln(
        hooks.hasOnStart
            ? 'final onStart = \$source.onStart;'
            : 'final onStart = null;',
      )
      ..writeln(
        hooks.hasOnStop
            ? 'final onStop = \$source.onStop;'
            : 'final onStop = null;',
      )
      ..writeln(
        hooks.hasOnError
            ? 'final onError = \$source.onError;'
            : 'final onError = null;',
      );
  } else {
    hooksBuffer
      ..writeln()
      ..writeln('final onStart = null;')
      ..writeln('final onStop = null;')
      ..writeln('final onError = null;');
  }

  final main = _generateMain(config);
  final files = <GeneratedFile>[
    GeneratedFile(path: 'app.g.dart', content: app.toString()),
    GeneratedFile(path: 'hooks.g.dart', content: hooksBuffer.toString()),
    GeneratedFile(path: 'main.dart', content: main),
  ];
  switch (config.target) {
    case BuildTarget.cloudflare:
      files.add(
        const GeneratedFile(path: '_worker.mjs', content: _cloudflareWorker),
      );
    case BuildTarget.vercel:
      files.add(
        const GeneratedFile(path: 'api/index.mjs', content: _vercelEntry),
      );
      files.add(
        const GeneratedFile(path: 'vercel.json', content: _vercelConfig),
      );
      files.add(
        const GeneratedFile(path: 'package.json', content: _vercelPackageJson),
      );
    default:
      break;
  }
  return files;
}

int _compareRouteEntries(RouteEntry a, RouteEntry b) {
  if (a.method == null && b.method != null) {
    return -1;
  }
  if (a.method != null && b.method == null) {
    return 1;
  }
  return (a.method?.value ?? '').compareTo(b.method?.value ?? '');
}

String _escape(String value) =>
    value.replaceAll(r'$', r'\$').replaceAll("'", r"\'");

String _methodLiteral(HttpMethod method) => 'HttpMethod.${method.name}';

String _relativeImport(String filePath, {required String from}) {
  return p.relative(filePath, from: from).replaceAll('\\', '/');
}

String _generateMain(BuildConfig config) {
  final runtimeImport = switch (config.target) {
    BuildTarget.dart => "import 'package:osrv/runtime/dart.dart';",
    BuildTarget.node => "import 'package:osrv/runtime/node.dart';",
    BuildTarget.bun => "import 'package:osrv/runtime/bun.dart';",
    BuildTarget.cloudflare =>
      "import 'package:osrv/src/runtime/_internal/js/fetch_entry.dart' as \$entry;",
    BuildTarget.vercel =>
      "import 'package:osrv/esm.dart' as \$entry;",
  };

  final targetImport = switch (config.target) {
    BuildTarget.cloudflare =>
      "import 'package:osrv/src/runtime/cloudflare/worker_js.dart' as \$target;",
    _ => null,
  };

  final body = switch (config.target) {
    BuildTarget.dart =>
      "Future<void> main() async {\n"
          "  final server = Server(\n"
          "    fetch: app.fetch,\n"
          "    onStart: \$hooks.onStart,\n"
          "    onStop: \$hooks.onStop,\n"
          "    onError: \$hooks.onError,\n"
          "  );\n"
          "  final runtime = await serve(server, DartRuntimeConfig(host: '${_escape(config.host)}', port: ${config.port}));\n"
          "  await runtime.closed;\n"
          "}",
    BuildTarget.node =>
      "Future<void> main() async {\n"
          "  final server = Server(\n"
          "    fetch: app.fetch,\n"
          "    onStart: \$hooks.onStart,\n"
          "    onStop: \$hooks.onStop,\n"
          "    onError: \$hooks.onError,\n"
          "  );\n"
          "  final runtime = await serve(server, NodeRuntimeConfig(host: '${_escape(config.host)}', port: ${config.port}));\n"
          "  await runtime.closed;\n"
          "}",
    BuildTarget.bun =>
      "Future<void> main() async {\n"
          "  final server = Server(\n"
          "    fetch: app.fetch,\n"
          "    onStart: \$hooks.onStart,\n"
          "    onStop: \$hooks.onStop,\n"
          "    onError: \$hooks.onError,\n"
          "  );\n"
          "  final runtime = await serve(server, BunRuntimeConfig(host: '${_escape(config.host)}', port: ${config.port}));\n"
          "  await runtime.closed;\n"
          "}",
    BuildTarget.cloudflare =>
      "void main() {\n"
          "  final server = Server(\n"
          "    fetch: app.fetch,\n"
          "    onStart: \$hooks.onStart,\n"
          "    onStop: \$hooks.onStop,\n"
          "    onError: \$hooks.onError,\n"
          "  );\n"
          "  \$entry.defineFetchEntry(\$target.createCloudflareFetchEntry(server));\n"
          "}",
    BuildTarget.vercel =>
      "void main() {\n"
          "  final server = Server(\n"
          "    fetch: app.fetch,\n"
          "    onStart: \$hooks.onStart,\n"
          "    onStop: \$hooks.onStop,\n"
          "    onError: \$hooks.onError,\n"
          "  );\n"
          "  \$entry.defineFetchEntry(server, runtime: \$entry.FetchEntryRuntime.vercel);\n"
          "}",
  };

  final buffer = StringBuffer()
    ..writeln("// Generated by spry - do not edit.")
    ..writeln("import 'package:osrv/osrv.dart';")
    ..writeln(runtimeImport);
  if (targetImport != null) {
    buffer.writeln(targetImport);
  }
  buffer
    ..writeln("import 'hooks.g.dart' as \$hooks;")
    ..writeln("import 'app.g.dart';")
    ..writeln()
    ..write(body);
  return buffer.toString();
}

const _cloudflareWorker = """
// Generated by spry - do not edit.
import './main.js';

export default { fetch: globalThis.__osrv_fetch__ };
""";

const _vercelEntry = """
// Generated by spry - do not edit.
globalThis.self ??= globalThis;
import '../main.js';

export default { fetch: globalThis.__osrv_fetch__ };
""";

const _vercelConfig = """
{
  "\$schema": "https://openapi.vercel.sh/vercel.json",
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/api/index"
    }
  ]
}
""";

const _vercelPackageJson = """
{
  "private": true,
  "type": "module",
  "dependencies": {
    "@vercel/functions": "^3.4.3"
  }
}
""";
