import 'package:path/path.dart' as p;

import '../../config.dart';

import 'config.dart';
import 'generated_file.dart';

/// Runtime-specific generation details for a build target.
final class TargetSpec {
  /// Creates a target specification.
  const TargetSpec({
    required this.runtimeImport,
    required this.mainBody,
    this.compiledJsOutput,
    this.extraFiles = const [],
  });

  /// Import used by the generated `main.dart`.
  final String runtimeImport;

  /// Generated `main()` body.
  final String mainBody;

  /// Output path for compiled JavaScript, when applicable.
  final String? compiledJsOutput;

  /// Extra generated files required by the target.
  final List<GeneratedFile> extraFiles;
}

/// Builds the generation specification for [config.target].
TargetSpec buildTargetSpec(BuildConfig config) {
  return switch (config.target) {
    BuildTarget.dart => TargetSpec(
      runtimeImport: "import 'package:osrv/runtime/dart.dart';",
      mainBody: _serveBody(host: config.host, port: config.port),
    ),
    BuildTarget.node => TargetSpec(
      runtimeImport: "import 'package:osrv/runtime/node.dart';",
      mainBody: _serveBody(host: config.host, port: config.port),
      compiledJsOutput: p.join(config.outputDir, 'runtime', 'main.js'),
      extraFiles: const [GeneratedFile(path: 'main.cjs', content: _nodeEntry)],
    ),
    BuildTarget.bun => TargetSpec(
      runtimeImport: "import 'package:osrv/runtime/bun.dart';",
      mainBody: _serveBody(host: config.host, port: config.port),
      compiledJsOutput: p.join(config.outputDir, 'main.js'),
    ),
    BuildTarget.cloudflare => TargetSpec(
      runtimeImport:
          "import 'package:osrv/runtime/cloudflare.dart' as \$entry;",
      mainBody: _fetchEntryBody(r'$entry.defineFetchExport(server);'),
      compiledJsOutput: p.join(config.outputDir, 'main.js'),
      extraFiles: [
        GeneratedFile(path: 'cloudflare.mjs', content: _cloudflareWorker),
      ],
    ),
    BuildTarget.vercel => TargetSpec(
      runtimeImport: "import 'package:osrv/runtime/vercel.dart' as \$entry;",
      mainBody: _fetchEntryBody(r'$entry.defineFetchExport(server);'),
      compiledJsOutput: p.join(
        config.outputDir,
        'vercel',
        'runtime',
        'main.js',
      ),
      extraFiles: const [
        GeneratedFile(path: 'vercel/api/index.mjs', content: _vercelEntry),
        GeneratedFile(path: 'vercel/vercel.json', content: _vercelConfig),
        GeneratedFile(path: 'vercel/package.json', content: _vercelPackageJson),
      ],
    ),
  };
}

/// Returns the JavaScript output path for the target in [config].
String compiledJsOutput(BuildConfig config) {
  return buildTargetSpec(config).compiledJsOutput ??
      p.join(config.outputDir, 'main.js');
}

String _serveBody({required String host, required int port}) {
  return "Future<void> main() async {\n"
      "  final server = Server(\n"
      "    fetch: app.fetch,\n"
      "    onStart: \$hooks.onStart,\n"
      "    onStop: \$hooks.onStop,\n"
      "    onError: \$hooks.onError,\n"
      "  );\n"
      "  final runtime = await serve(\n"
      "    server,\n"
      "    host: '${_escape(host)}',\n"
      "    port: $port,\n"
      "  );\n"
      "  await runtime.closed;\n"
      "}";
}

String _fetchEntryBody(String defineFetchEntryCall) {
  return "void main() {\n"
      "  final server = Server(\n"
      "    fetch: app.fetch,\n"
      "    onStart: \$hooks.onStart,\n"
      "    onStop: \$hooks.onStop,\n"
      "    onError: \$hooks.onError,\n"
      "  );\n"
      "  $defineFetchEntryCall\n"
      "}";
}

String _escape(String value) =>
    value.replaceAll(r'$', r'\$').replaceAll("'", r"\'");

const _cloudflareWorker = """
// Generated by spry - do not edit.
import './main.js';

export default { fetch: globalThis.__osrv_fetch__ };
""";

const _nodeEntry = """
// Generated by spry - do not edit.
globalThis.self ??= globalThis;
require('./runtime/main.js');
""";

const _vercelEntry = """
// Generated by spry - do not edit.
globalThis.self ??= globalThis;
import '../runtime/main.js';

export default { fetch: globalThis.__osrv_fetch__ };
""";

const _vercelConfig = """
{
  "\$schema": "https://openapi.vercel.sh/vercel.json",
  "rewrites": [
    {
      "source": "/(.*)",
      "destination": "/api"
    }
  ]
}
""";

const _vercelPackageJson = """
{
  "private": true,
  "dependencies": {
    "@vercel/functions": "^3.4.3"
  }
}
""";
