// Generated by spry - do not edit.
import 'package:spry/src/app.dart';
import 'package:spry/src/error_route.dart';
import 'package:spry/src/middleware.dart';
import 'package:ht/ht.dart' show HttpMethod;
import '../middleware/01_logger.dart' as $i0;
import '../routes/[...slug].dart' as $i1;
import '../routes/_error.dart' as $i2;
import '../routes/_middleware.dart' as $i3;
import '../routes/about.get.dart' as $i4;
import '../routes/index.dart' as $i5;
import '../routes/users/[id].dart' as $i6;

final app = Spry(
  routes: {
    '/': {
      null: $i5.handler,
    },
    '/about': {
      HttpMethod.get: $i4.handler,
    },
    '/users/:id': {
      null: $i6.handler,
    },
  },
  middleware: [
    MiddlewareRoute(path: '/*', handler: $i0.middleware),
    MiddlewareRoute(path: '/*', handler: $i3.middleware),
  ],
  errors: [
    ErrorRoute(path: '/*', handler: $i2.onError),
  ],
  fallback: {
    null: $i1.handler,
  },
);
