// Generated by spry - do not edit.
import 'package:osrv/osrv.dart';
import 'package:osrv/runtime/dart.dart';
import 'hooks.g.dart' as $hooks;
import 'app.g.dart';

Future<void> main() async {
  final server = Server(
    fetch: app.fetch,
    onStart: $hooks.onStart,
    onStop: $hooks.onStop,
    onError: $hooks.onError,
  );
  final runtime = await serve(server, DartRuntimeConfig(host: '127.0.0.1', port: 4000));
  await runtime.closed;
}