name: simple_io
description: Spry simple IO example app.
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  spry:
    path: ../../packages/spry

dev_dependencies:
  lints: ^3.0.0
