name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [spry, spry_cookie]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
        working-directory: packages/${{ matrix.packages }}
      - name: Analyze
        run: dart analyze
        working-directory: packages/${{ matrix.packages }}
      - name: run tests
        run: dart test
        working-directory: packages/${{ matrix.packages }}
